import React, { useState } from 'react';
import { ScrollView, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { C } from './theme';
import { diaryQuestions, lifestyleSections, mentalPlaylists, stoicPrinciples, tellLessons, warRoomTriggers } from './content';
import { Label, PremiumButton, Serif } from './ui';
import { s } from './styles';
import { GameState, Module, moduleMeta } from './types';

export function ModuleOverlay({ module, close }: { module:Module; close:()=>void }) {
  const [playlist,setPlaylist]=useState('a-game');
  const [reaction,setReaction]=useState<number|null>(null);
  const [diaryIndex,setDiaryIndex]=useState(0);
  const [diaryText,setDiaryText]=useState('');
  const [vaccine,setVaccine]=useState('');
  const meta=moduleMeta[module];

  let body:React.ReactNode;
  if(module==='war') body=<View style={s.moduleContent}><View style={s.panel}><Label>EMOTIONAL HEATMAP</Label><Serif style={s.overlayHeadline}>Onde seu C-Game costuma começar?</Serif><View style={s.heatmap}>{Array.from({length:28}).map((_,i)=><View key={i} style={[s.heat,{opacity:.18+((i*37)%80)/100}]}/>)}</View><AppText style={s.body}>Janela crítica atual: 03h05 → 03h45. Gatilho mais frequente: fadiga + urgência após perda.</AppText></View><View style={s.moduleAction}><View><Label>BATTLE DIARY</Label><Serif style={s.actionTitle}>Audite execução, não ego.</Serif></View><Ionicons name="chevron-forward" size={18} color={C.goldLight}/></View><View style={s.moduleAction}><View><Label>PSYCHOLOGICAL VACCINES</Label><Serif style={s.actionTitle}>Dessensibilize a resposta à variância.</Serif></View><Ionicons name="chevron-forward" size={18} color={C.goldLight}/></View></View>;
  else if(module==='behavior') body=<View style={s.moduleContent}><View style={s.panel}><Label>EDITORIAL RULE</Label><Serif style={s.overlayHeadline}>Baseline antes da interpretação.</Serif><AppText style={s.body}>Tells são evidência contextual e probabilística. Nenhum gesto isolado prova força ou blefe.</AppText></View>{tellLessons.map((x,i)=><View key={x.title} style={s.lesson}><AppText style={s.moduleN}>0{i+1}</AppText><View style={s.flex}><Label>{x.title}</Label><AppText style={s.lessonBody}>{x.body}</AppText></View></View>)}</View>;
  else if(module==='gym') body=<View style={s.moduleContent}><TouchableOpacity style={[s.reaction,reaction!==null&&s.reactionDone]} onPress={()=>setReaction(reaction===null?284:null)}><Label>REACTION TEST</Label><Serif style={s.reactionValue}>{reaction===null?'READY':`${reaction} ms`}</Serif><AppText style={s.body}>{reaction===null?'Toque para iniciar.':'Baseline pessoal: 301 ms · Hoje: -17 ms'}</AppText></TouchableOpacity><View style={s.moduleAction}><View><Label>RANGE MEMORY</Label><Serif style={s.actionTitle}>Memória operacional de cartas e ranges.</Serif></View><Ionicons name="chevron-forward" size={18} color={C.goldLight}/></View><View style={s.moduleAction}><View><Label>ATTENTION SHIFT</Label><Serif style={s.actionTitle}>Troca de foco sob pressão.</Serif></View><Ionicons name="chevron-forward" size={18} color={C.goldLight}/></View></View>;
  else if(module==='lifestyle') body=<View style={s.moduleContent}>{lifestyleSections.map(x=><View key={x.title} style={s.lifestyle}><Label>{x.title}</Label><Serif style={s.actionTitle}>{x.subtitle}</Serif><AppText style={s.lessonBody}>{x.body}</AppText></View>)}</View>;
  else if(module==='audio') body=<View style={s.moduleContent}>{mentalPlaylists.map(p=><TouchableOpacity key={p.id} onPress={()=>setPlaylist(p.id)} style={[s.playlist,playlist===p.id&&s.playlistActive]}><View style={[s.playCircle,playlist===p.id&&s.playCircleActive]}><Ionicons name={playlist===p.id?'pause':'play'} size={17} color={playlist===p.id?C.ink:C.goldLight}/></View><View style={s.flex}><View style={s.rowBetween}><Serif style={s.playlistTitle}>{p.title}</Serif><AppText style={s.goldText}>{p.duration}</AppText></View><Label>{p.mode}</Label><AppText style={s.playlistBody}>{p.description}</AppText>{playlist===p.id?<Serif style={s.nowCue}>“{p.cue}”</Serif>:null}</View></TouchableOpacity>)}</View>;
  else if(module==='diary') body=<View style={s.moduleContent}><View style={s.panel}><Label>QUESTION {diaryIndex+1} / {diaryQuestions.length}</Label><Serif style={s.diaryQuestion}>{diaryQuestions[diaryIndex]}</Serif><AppTextInput value={diaryText} onChangeText={setDiaryText} multiline placeholder="Escreva ou grave sua resposta..." placeholderTextColor={C.dim} style={s.diaryInput}/><View style={s.diaryNav}><PremiumButton label="←" secondary onPress={()=>setDiaryIndex(i=>Math.max(0,i-1))}/><PremiumButton label="→" secondary onPress={()=>setDiaryIndex(i=>Math.min(diaryQuestions.length-1,i+1))}/></View></View></View>;
  else if(module==='vaccines') body=<View style={s.moduleContent}><View style={s.panel}><Label>BAD BEAT VACCINE / 01</Label><Serif style={s.overlayHeadline}>AA vs KK · all-in pré-flop</Serif><AppText style={s.dangerText}>RIVER: K</AppText><AppText style={s.body}>Seu resultado foi negativo. A decisão anterior continua sendo avaliada pelo processo, não pelo river.</AppText></View>{['Jogo sempre azarado.','Não deveria ter ido all-in.','Decisão correta, resultado desfavorável.','Preciso recuperar agora.'].map(x=><TouchableOpacity key={x} onPress={()=>setVaccine(x)} style={[s.option,vaccine===x&&s.optionActive]}><AppText style={[s.optionText,vaccine===x&&s.optionTextActive]}>{x}</AppText></TouchableOpacity>)}</View>;
  else body=<View style={s.moduleContent}>{stoicPrinciples.map(x=><View key={x.title} style={s.stoic}><Label>{x.title}</Label><Serif style={s.stoicText}>{x.body}</Serif></View>)}</View>;

  return <View style={s.overlay}><SafeAreaView style={s.flex}><View style={s.overlayHeader}><View><Label>{meta.subtitle}</Label><Serif style={s.overlayTitle}>{meta.title}</Serif></View><TouchableOpacity onPress={close} style={s.close}><Ionicons name="close" size={25} color={C.ivory}/></TouchableOpacity></View><ScrollView contentContainerStyle={s.overlayScroll}>{body}</ScrollView></SafeAreaView></View>;
}

export function BreakOverlay({ close }: { close:()=>void }) {
  const [step,setStep]=useState(0); const steps=[['01:00','DESCARGA FÍSICA','Solte mandíbula, ombros e mãos. Faça três expirações longas.'],['02:00','RESPIRAÇÃO & ÁGUA','Respiração baixa. Hidrate sem pressa. Reduza ativação, não atenção.'],['03:00','MOBILIDADE','Levante. Abra o peito. Mova quadris, pescoço e punhos.'],['04:00','REALINHAMENTO','Nova hora. Novo bloco. Uma decisão por vez.']];
  return <View style={s.overlay}><SafeAreaView style={s.breakSafe}><View style={s.rowBetween}><Label>BREAK AUDIO / 4:00</Label><TouchableOpacity onPress={close} style={s.close}><Ionicons name="close" size={25} color={C.ivory}/></TouchableOpacity></View><View style={s.breakCenter}><View style={s.breathe}><View style={s.breatheInner}/></View><AppText style={s.goldText}>{steps[step][0]}</AppText><Serif style={s.breakTitle}>{steps[step][1]}</Serif><AppText style={s.breakCopy}>{steps[step][2]}</AppText><View style={s.breakDots}>{steps.map((_,i)=><View key={i} style={[s.breakDot,i===step&&s.breakDotActive]}/>)}</View></View><PremiumButton label={step===3?'RETURN TO SESSION':'NEXT MINUTE'} onPress={()=>step===3?close():setStep(step+1)}/></SafeAreaView></View>;
}

export function CheckinOverlay({ close }: { close:()=>void }) {
  const [state,setState]=useState<GameState>('B'); const [trigger,setTrigger]=useState('');
  return <View style={s.overlay}><SafeAreaView style={s.checkinSafe}><View style={s.rowBetween}><View><Label>MICRO CHECK-IN</Label><Serif style={s.overlayTitle}>Estado atual</Serif></View><TouchableOpacity onPress={close} style={s.close}><Ionicons name="close" size={25} color={C.ivory}/></TouchableOpacity></View><View style={s.panel}><Label>A / B / C GAME</Label><View style={s.stateRow}>{(['A','B','C'] as GameState[]).map(x=><TouchableOpacity key={x} onPress={()=>setState(x)} style={[s.stateButton,state===x&&s.stateButtonActive]}><AppText style={[s.stateText,state===x&&s.stateTextActive]}>{x}</AppText></TouchableOpacity>)}</View></View><View style={s.panel}><Label>GATILHO / ESTADO</Label><View style={s.chips}>{warRoomTriggers.map(x=><TouchableOpacity key={x} onPress={()=>setTrigger(x)} style={[s.chip,trigger===x&&s.chipActive]}><AppText style={[s.chipText,trigger===x&&s.chipTextActive]}>{x}</AppText></TouchableOpacity>)}</View></View><PremiumButton label="SAVE CHECK-IN" onPress={close}/></SafeAreaView></View>;
}

export function SOSOverlay({ close, goCoach }: { close:()=>void; goCoach:()=>void }) {
  const [step,setStep]=useState(0); const [trigger,setTrigger]=useState(''); const steps=[['PARE.','A mão terminou. O resultado não pode mais ser alterado. A próxima decisão ainda pode.'],['RESPIRAÇÃO.','Solte mandíbula, ombros e mãos. Expire mais longo do que inspira.'],['SEPARE.','Decisão e resultado são variáveis diferentes. Não use a última mão para justificar a próxima.'],['RETORNE.','Você não precisa recuperar fichas agora. Precisa recuperar qualidade de decisão.']];
  return <View style={s.sos}><SafeAreaView style={s.sosSafe}><View style={s.rowBetween}><Label>SOS / INTERRUPTION PROTOCOL</Label><TouchableOpacity onPress={close} style={s.close}><Ionicons name="close" size={25} color={C.ivory}/></TouchableOpacity></View><View style={s.sosCenter}><View style={s.breathe}><View style={s.breatheInner}/></View><Serif style={s.sosTitle}>{steps[step][0]}</Serif><AppText style={s.sosCopy}>{steps[step][1]}</AppText><AppText style={s.sosTimer}>01:00</AppText>{step>=2?<View style={s.sosTriggerWrap}><Label>O QUE ACONTECEU?</Label><View style={s.chips}>{warRoomTriggers.map(x=><TouchableOpacity key={x} onPress={()=>setTrigger(x)} style={[s.chip,trigger===x&&s.chipActive]}><AppText style={[s.chipText,trigger===x&&s.chipTextActive]}>{x}</AppText></TouchableOpacity>)}</View></View>:null}</View><View style={s.sosActions}><PremiumButton label={step===3?'VOLTAR À SESSÃO':'CONTINUAR'} onPress={()=>step===3?close():setStep(step+1)}/><PremiumButton label="FALAR COM COACH" secondary icon="mic-outline" onPress={goCoach}/></View></SafeAreaView></View>;
}
